/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uas_04_arsyaalifianwidiatmoko;

/**
 *
 * @author Lenovo
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public static HomePage instance;
    LoginRegister lr = LoginRegister.instance;
    
    
    public HomePage() {
        initComponents();
        Panel.setVisible(false);
        System.out.println(lr.iduser);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Panel = new javax.swing.JPanel();
        userPanel = new javax.swing.JPanel();
        Home1 = new javax.swing.JLabel();
        Setting1 = new javax.swing.JLabel();
        Account1 = new javax.swing.JLabel();
        Bayar = new javax.swing.JLabel();
        LihatPenggunaan = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Adminpanel = new javax.swing.JPanel();
        Home = new javax.swing.JLabel();
        Setting = new javax.swing.JLabel();
        Account = new javax.swing.JLabel();
        DaftarUser = new javax.swing.JLabel();
        DaftarTagihan = new javax.swing.JLabel();
        DaftarBayar = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        HomeCanvas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel4MouseReleased(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 70, 50, 50));

        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel6MouseReleased(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 40, 50));

        Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        userPanel.add(Home1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 30, 20));
        userPanel.add(Setting1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 70, 20));

        Account1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Account1MouseReleased(evt);
            }
        });
        userPanel.add(Account1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 70, 20));
        userPanel.add(Bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 70, 10));

        LihatPenggunaan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                LihatPenggunaanMouseReleased(evt);
            }
        });
        userPanel.add(LihatPenggunaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 10));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/UserMenu.jpg"))); // NOI18N
        userPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 150));

        Panel.add(userPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 150));

        Adminpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Adminpanel.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 30, 20));
        Adminpanel.add(Setting, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 70, 20));

        Account.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                AccountMouseReleased(evt);
            }
        });
        Adminpanel.add(Account, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 70, 20));

        DaftarUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                DaftarUserMouseReleased(evt);
            }
        });
        Adminpanel.add(DaftarUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 70, 20));
        Adminpanel.add(DaftarTagihan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 70, 20));
        Adminpanel.add(DaftarBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 60, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/AdminMenu.jpg"))); // NOI18N
        Adminpanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Panel.add(Adminpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 150));

        getContentPane().add(Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 100, 150));

        HomeCanvas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Menu.jpg"))); // NOI18N
        HomeCanvas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                HomeCanvasMouseReleased(evt);
            }
        });
        getContentPane().add(HomeCanvas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseReleased
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel6MouseReleased

    private void jLabel4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseReleased
        // TODO add your handling code here:
        Panel.setVisible(true);
        FirstPage fp = FirstPage.instance;
        if (fp.as.equals("Admin")) {
            Adminpanel.setVisible(true);
            userPanel.setVisible(false);
        }
        if (fp.as.equals("User")) {
            Adminpanel.setVisible(false);
            userPanel.setVisible(true);
        }
        
    }//GEN-LAST:event_jLabel4MouseReleased

    private void HomeCanvasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeCanvasMouseReleased
        // TODO add your handling code here:
        Panel.setVisible(false);
    }//GEN-LAST:event_HomeCanvasMouseReleased

    private void DaftarUserMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DaftarUserMouseReleased
        // TODO add your handling code here:
        UserList ul = new UserList();
        ul.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DaftarUserMouseReleased

    private void AccountMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccountMouseReleased
        // TODO add your handling code here:
        AccControl ac = new AccControl();
        ac.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AccountMouseReleased

    private void LihatPenggunaanMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LihatPenggunaanMouseReleased
        // TODO add your handling code here:
        UPenggunaan up = new UPenggunaan();
        up.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LihatPenggunaanMouseReleased

    private void Account1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Account1MouseReleased
        // TODO add your handling code here:
        AccControl ac = new AccControl();
        ac.setVisible(true);
    }//GEN-LAST:event_Account1MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Account;
    private javax.swing.JLabel Account1;
    private javax.swing.JPanel Adminpanel;
    private javax.swing.JLabel Bayar;
    private javax.swing.JLabel DaftarBayar;
    private javax.swing.JLabel DaftarTagihan;
    private javax.swing.JLabel DaftarUser;
    private javax.swing.JLabel Home;
    private javax.swing.JLabel Home1;
    private javax.swing.JLabel HomeCanvas;
    private javax.swing.JLabel LihatPenggunaan;
    private javax.swing.JPanel Panel;
    private javax.swing.JLabel Setting;
    private javax.swing.JLabel Setting1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel userPanel;
    // End of variables declaration//GEN-END:variables
}
