/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uas_04_arsyaalifianwidiatmoko;

import java.sql.Connection;
import java.awt.Color;
import java.awt.Font;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class UserList extends javax.swing.JFrame {

    /**
     * Creates new form UserList
     */
    FirstPage fp = FirstPage.instance;
    Connection con;

    public UserList() {
        initComponents();
        Panel.setVisible(false);
        con = Koneksi.getKoneksi("localhost", "3306", "root", "", "electric");
        ShowData();
    }
    DefaultTableModel dtm;

    void ShowData() {
        String[] kolom = {"NO, ID PELANGGAN", "USERNAME", "PASSWORD", "NO KWH", "NAMA PELANGGAN", "ALAMAT", "ID TARIF"};

        dtm = new DefaultTableModel(null, kolom);
        try {
            Statement stmt = con.createStatement();
            String query = "SELECT * FROM pelanggan";
            ResultSet rs = stmt.executeQuery(query);
            int no = 1;
            while (rs.next()) {
                String id_pelanggan = rs.getString("id_pelanggan");
                String username = rs.getString("username");
                String password = rs.getString("password");
                String no_kwh = rs.getString("no_kwh");
                String nama_pelanggan = rs.getString("nama_pelanggan");
                String alamat = rs.getString("alamat");
                String id_tarif = rs.getString("id_tarif");

                dtm.addRow(new String[]{no + "", id_pelanggan, username, password, no_kwh, nama_pelanggan, alamat, id_tarif});
                no++;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        tabel10.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Adminpanel = new javax.swing.JPanel();
        Home = new javax.swing.JLabel();
        Setting = new javax.swing.JLabel();
        Account = new javax.swing.JLabel();
        DaftarUser = new javax.swing.JLabel();
        DaftarTagihan = new javax.swing.JLabel();
        DaftarBayar = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        userPanel = new javax.swing.JPanel();
        Home1 = new javax.swing.JLabel();
        Setting1 = new javax.swing.JLabel();
        Account1 = new javax.swing.JLabel();
        DaftarUser1 = new javax.swing.JLabel();
        DaftarTagihan1 = new javax.swing.JLabel();
        DaftarBayar1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        tabel10 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel2MouseReleased(evt);
            }
        });
        Panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 30, 20));

        Adminpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Adminpanel.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 30, 20));
        Adminpanel.add(Setting, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 70, 20));
        Adminpanel.add(Account, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 70, 20));
        Adminpanel.add(DaftarUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 70, 20));
        Adminpanel.add(DaftarTagihan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 70, 20));
        Adminpanel.add(DaftarBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 60, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/AdminMenu.jpg"))); // NOI18N
        Adminpanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 150));

        Panel.add(Adminpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 150));

        userPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        userPanel.add(Home1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 30, 20));
        userPanel.add(Setting1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 70, 20));
        userPanel.add(Account1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 70, 20));
        userPanel.add(DaftarUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 70, 20));
        userPanel.add(DaftarTagihan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 70, 10));
        userPanel.add(DaftarBayar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 10));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/UserMenu.jpg"))); // NOI18N
        userPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 150));

        Panel.add(userPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 150));

        getContentPane().add(Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, 100, 150));

        tabel10.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        tabel10.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel10.setFocusable(false);
        tabel10.setRowHeight(25);
        tabel10.setSelectionBackground(new java.awt.Color(61, 126, 190));
        tabel10.setShowVerticalLines(false);
        tabel10.getTableHeader().setReorderingAllowed(false);
        tabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel10MouseClicked(evt);
            }
        });
        jScrollPane11.setViewportView(tabel10);

        getContentPane().add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 570, 350));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 480, -1));

        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel4MouseReleased(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 70, 50, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Menu.jpg"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel1MouseReleased(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel6MouseReleased(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 40, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseReleased
        // TODO add your handling code here:
        Panel.setVisible(true);
        
        if (fp.as.equals("Admin")) {
            Adminpanel.setVisible(true);
        }
        if (fp.as.equals("User")) {
            Adminpanel.setVisible(false);
            userPanel.setVisible(true);
        }

    }//GEN-LAST:event_jLabel4MouseReleased

    private void jLabel6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseReleased
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel6MouseReleased

    private void jLabel2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseReleased
        // TODO add your handling code here:
        HomePage hp = new HomePage();
        hp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseReleased

    int row;
    private void tabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel10MouseClicked
        row = tabel.getSelectedRow();
    }//GEN-LAST:event_tabel10MouseClicked

    private void jLabel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseReleased
        // TODO add your handling code here:
        Panel.setVisible(false);
    }//GEN-LAST:event_jLabel1MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Account;
    private javax.swing.JLabel Account1;
    private javax.swing.JPanel Adminpanel;
    private javax.swing.JLabel DaftarBayar;
    private javax.swing.JLabel DaftarBayar1;
    private javax.swing.JLabel DaftarTagihan;
    private javax.swing.JLabel DaftarTagihan1;
    private javax.swing.JLabel DaftarUser;
    private javax.swing.JLabel DaftarUser1;
    private javax.swing.JLabel Home;
    private javax.swing.JLabel Home1;
    private javax.swing.JPanel Panel;
    private javax.swing.JLabel Setting;
    private javax.swing.JLabel Setting1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable tabel;
    private javax.swing.JTable tabel1;
    private javax.swing.JTable tabel10;
    private javax.swing.JTable tabel2;
    private javax.swing.JTable tabel3;
    private javax.swing.JTable tabel4;
    private javax.swing.JTable tabel5;
    private javax.swing.JTable tabel6;
    private javax.swing.JTable tabel7;
    private javax.swing.JTable tabel8;
    private javax.swing.JTable tabel9;
    private javax.swing.JPanel userPanel;
    // End of variables declaration//GEN-END:variables
}
